#!/usr/bin/env bash
# Ping an IP address passed as an argument 5 times if argument count is not zero.
if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c5 "$1"
fi
